local reg = minetest.register_node
local mod = 'mystical_lands:'

-- earth nodes

local stone_nodes = {
  -- granite
  { description = "Hard coarse grain black stone", name = "hard_coarse_grain_black_stone", tile = "mystical_lands_hard_coarse_grain_black_stone.png" },
  { description = "Hard coarse grain dark blue stone", name = "hard_coarse_grain_dark_blue_stone", tile = "mystical_lands_hard_coarse_grain_dark_blue_stone.png" },
  { description = "Hard coarse grain dark gray stone", name = "hard_coarse_grain_dark_gray_stone", tile = "mystical_lands_hard_coarse_grain_dark_gray_stone.png" },
  { description = "Hard coarse grain dark olive stone", name = "hard_coarse_grain_dark_olive_stone", tile = "mystical_lands_hard_coarse_grain_dark_olive_stone.png" },
  { description = "Hard coarse grain gray blue stone", name = "hard_coarse_grain_gray_blue_stone", tile = "mystical_lands_hard_coarse_grain_gray_blue_stone.png" },
  { description = "Hard coarse grain light gray stone", name = "hard_coarse_grain_light_gray_stone", tile = "mystical_lands_hard_coarse_grain_light_gray_stone.png" },
  { description = "Hard coarse grain light olive stone", name = "hard_coarse_grain_light_olive_stone", tile = "mystical_lands_hard_coarse_grain_light_olive_stone.png" },
  { description = "Hard coarse grain pink stone", name = "hard_coarse_grain_pink_stone", tile = "mystical_lands_hard_coarse_grain_pink_stone.png" },
  { description = "Hard coarse grain red stone", name = "hard_coarse_grain_red_stone", tile = "mystical_lands_hard_coarse_grain_red_stone.png" },
  { description = "Hard coarse grain tan stone", name = "hard_coarse_grain_tan_stone", tile = "mystical_lands_hard_coarse_grain_tan_stone.png" },
  { description = "Hard coarse grain turquoise stone", name = "hard_coarse_grain_turquoise_stone", tile = "mystical_lands_hard_coarse_grain_turquoise_stone.png" },
  { description = "Hard coarse grain white stone", name = "hard_coarse_grain_white_stone", tile = "mystical_lands_hard_coarse_grain_white_stone.png" },
  { description = "Hard fine grain black stone", name = "hard_fine_grain_black_stone", tile = "mystical_lands_hard_fine_grain_black_stone.png" },
  { description = "Hard fine grain dark blue stone", name = "hard_fine_grain_dark_blue_stone", tile = "mystical_lands_hard_fine_grain_dark_blue_stone.png" },
  { description = "Hard fine grain dark gray stone", name = "hard_fine_grain_dark_gray_stone", tile = "mystical_lands_hard_fine_grain_dark_gray_stone.png" },
  { description = "Hard fine grain dark olive stone", name = "hard_fine_grain_dark_olive_stone", tile = "mystical_lands_hard_fine_grain_dark_olive_stone.png" },
  { description = "Hard fine grain gray blue stone", name = "hard_fine_grain_gray_blue_stone", tile = "mystical_lands_hard_fine_grain_gray_blue_stone.png" },
  { description = "Hard fine grain light gray stone", name = "hard_fine_grain_light_gray_stone", tile = "mystical_lands_hard_fine_grain_light_gray_stone.png" },
  { description = "Hard fine grain light olive stone", name = "hard_fine_grain_light_olive_stone", tile = "mystical_lands_hard_fine_grain_light_olive_stone.png" },
  { description = "Hard fine grain pink stone", name = "hard_fine_grain_pink_stone", tile = "mystical_lands_hard_fine_grain_pink_stone.png" },
  { description = "Hard fine grain red stone", name = "hard_fine_grain_red_stone", tile = "mystical_lands_hard_fine_grain_red_stone.png" },
  { description = "Hard fine grain tan stone", name = "hard_fine_grain_tan_stone", tile = "mystical_lands_hard_fine_grain_tan_stone.png" },
  { description = "Hard fine grain turquoise stone", name = "hard_fine_grain_turquoise_stone", tile = "mystical_lands_hard_fine_grain_turquoise_stone.png" },
  { description = "Hard fine grain white stone", name = "hard_fine_grain_white_stone", tile = "mystical_lands_hard_fine_grain_white_stone.png" },
  { description = "Hard glassy black stone", name = "hard_glassy_black_stone", tile = "mystical_lands_hard_glassy_black_stone.png" },
  { description = "Hard glassy dark blue stone", name = "hard_glassy_dark_blue_stone", tile = "mystical_lands_hard_glassy_dark_blue_stone.png" },
  { description = "Hard glassy dark gray stone", name = "hard_glassy_dark_gray_stone", tile = "mystical_lands_hard_glassy_dark_gray_stone.png" },
  { description = "Hard glassy dark olive stone", name = "hard_glassy_dark_olive_stone", tile = "mystical_lands_hard_glassy_dark_olive_stone.png" },
  { description = "Hard glassy gray blue stone", name = "hard_glassy_gray_blue_stone", tile = "mystical_lands_hard_glassy_gray_blue_stone.png" },
  { description = "Hard glassy light gray stone", name = "hard_glassy_light_gray_stone", tile = "mystical_lands_hard_glassy_light_gray_stone.png" },
  { description = "Hard glassy light olive stone", name = "hard_glassy_light_olive_stone", tile = "mystical_lands_hard_glassy_light_olive_stone.png" },
  { description = "Hard glassy pink stone", name = "hard_glassy_pink_stone", tile = "mystical_lands_hard_glassy_pink_stone.png" },
  { description = "Hard glassy red stone", name = "hard_glassy_red_stone", tile = "mystical_lands_hard_glassy_red_stone.png" },
  { description = "Hard glassy tan stone", name = "hard_glassy_tan_stone", tile = "mystical_lands_hard_glassy_tan_stone.png" },
  { description = "Hard glassy turquoise stone", name = "hard_glassy_turquoise_stone", tile = "mystical_lands_hard_glassy_turquoise_stone.png" },
  { description = "Hard glassy white stone", name = "hard_glassy_white_stone", tile = "mystical_lands_hard_glassy_white_stone.png" },
  { description = "Hard smooth black stone", name = "hard_smooth_black_stone", tile = "mystical_lands_hard_smooth_black_stone.png" },
  { description = "Hard smooth dark blue stone", name = "hard_smooth_dark_blue_stone", tile = "mystical_lands_hard_smooth_dark_blue_stone.png" },
  { description = "Hard smooth dark gray stone", name = "hard_smooth_dark_gray_stone", tile = "mystical_lands_hard_smooth_dark_gray_stone.png" },
  { description = "Hard smooth dark olive stone", name = "hard_smooth_dark_olive_stone", tile = "mystical_lands_hard_smooth_dark_olive_stone.png" },
  { description = "Hard smooth gray blue stone", name = "hard_smooth_gray_blue_stone", tile = "mystical_lands_hard_smooth_gray_blue_stone.png" },
  { description = "Hard smooth light gray stone", name = "hard_smooth_light_gray_stone", tile = "mystical_lands_hard_smooth_light_gray_stone.png" },
  { description = "Hard smooth light olive stone", name = "hard_smooth_light_olive_stone", tile = "mystical_lands_hard_smooth_light_olive_stone.png" },
  { description = "Hard smooth pink stone", name = "hard_smooth_pink_stone", tile = "mystical_lands_hard_smooth_pink_stone.png" },
  { description = "Hard smooth red stone", name = "hard_smooth_red_stone", tile = "mystical_lands_hard_smooth_red_stone.png" },
  { description = "Hard smooth tan stone", name = "hard_smooth_tan_stone", tile = "mystical_lands_hard_smooth_tan_stone.png" },
  { description = "Hard smooth turquoise stone", name = "hard_smooth_turquoise_stone", tile = "mystical_lands_hard_smooth_turquoise_stone.png" },
  { description = "Hard smooth white stone", name = "hard_smooth_white_stone", tile = "mystical_lands_hard_smooth_white_stone.png" },
  { description = "Soft coarse grain black stone", name = "soft_coarse_grain_black_stone", tile = "mystical_lands_soft_coarse_grain_black_stone.png" },
  { description = "Soft coarse grain dark blue stone", name = "soft_coarse_grain_dark_blue_stone", tile = "mystical_lands_soft_coarse_grain_dark_blue_stone.png" },
  { description = "Soft coarse grain dark gray stone", name = "soft_coarse_grain_dark_gray_stone", tile = "mystical_lands_soft_coarse_grain_dark_gray_stone.png" },
  { description = "Soft coarse grain dark olive stone", name = "soft_coarse_grain_dark_olive_stone", tile = "mystical_lands_soft_coarse_grain_dark_olive_stone.png" },
  { description = "Soft coarse grain gray blue stone", name = "soft_coarse_grain_gray_blue_stone", tile = "mystical_lands_soft_coarse_grain_gray_blue_stone.png" },
  { description = "Soft coarse grain light gray stone", name = "soft_coarse_grain_light_gray_stone", tile = "mystical_lands_soft_coarse_grain_light_gray_stone.png" },
  { description = "Soft coarse grain light olive stone", name = "soft_coarse_grain_light_olive_stone", tile = "mystical_lands_soft_coarse_grain_light_olive_stone.png" },
  { description = "Soft coarse grain pink stone", name = "soft_coarse_grain_pink_stone", tile = "mystical_lands_soft_coarse_grain_pink_stone.png" },
  { description = "Soft coarse grain red stone", name = "soft_coarse_grain_red_stone", tile = "mystical_lands_soft_coarse_grain_red_stone.png" },
  { description = "Soft coarse grain tan stone", name = "soft_coarse_grain_tan_stone", tile = "mystical_lands_soft_coarse_grain_tan_stone.png" },
  { description = "Soft coarse grain turquoise stone", name = "soft_coarse_grain_turquoise_stone", tile = "mystical_lands_soft_coarse_grain_turquoise_stone.png" },
  { description = "Soft coarse grain white stone", name = "soft_coarse_grain_white_stone", tile = "mystical_lands_soft_coarse_grain_white_stone.png" },
  { description = "Soft fine grain black stone", name = "soft_fine_grain_black_stone", tile = "mystical_lands_soft_fine_grain_black_stone.png" },
  { description = "Soft fine grain dark blue stone", name = "soft_fine_grain_dark_blue_stone", tile = "mystical_lands_soft_fine_grain_dark_blue_stone.png" },
  { description = "Soft fine grain dark gray stone", name = "soft_fine_grain_dark_gray_stone", tile = "mystical_lands_soft_fine_grain_dark_gray_stone.png" },
  { description = "Soft fine grain dark olive stone", name = "soft_fine_grain_dark_olive_stone", tile = "mystical_lands_soft_fine_grain_dark_olive_stone.png" },
  { description = "Soft fine grain gray blue stone", name = "soft_fine_grain_gray_blue_stone", tile = "mystical_lands_soft_fine_grain_gray_blue_stone.png" },
  { description = "Soft fine grain light gray stone", name = "soft_fine_grain_light_gray_stone", tile = "mystical_lands_soft_fine_grain_light_gray_stone.png" },
  { description = "Soft fine grain light olive stone", name = "soft_fine_grain_light_olive_stone", tile = "mystical_lands_soft_fine_grain_light_olive_stone.png" },
  { description = "Soft fine grain pink stone", name = "soft_fine_grain_pink_stone", tile = "mystical_lands_soft_fine_grain_pink_stone.png" },
  { description = "Soft fine grain red stone", name = "soft_fine_grain_red_stone", tile = "mystical_lands_soft_fine_grain_red_stone.png" },
  { description = "Soft fine grain tan stone", name = "soft_fine_grain_tan_stone", tile = "mystical_lands_soft_fine_grain_tan_stone.png" },
  { description = "Soft fine grain turquoise stone", name = "soft_fine_grain_turquoise_stone", tile = "mystical_lands_soft_fine_grain_turquoise_stone.png" },
  { description = "Soft fine grain white stone", name = "soft_fine_grain_white_stone", tile = "mystical_lands_soft_fine_grain_white_stone.png" },
  { description = "Soft glassy black stone", name = "soft_glassy_black_stone", tile = "mystical_lands_soft_glassy_black_stone.png" },
  { description = "Soft glassy dark blue stone", name = "soft_glassy_dark_blue_stone", tile = "mystical_lands_soft_glassy_dark_blue_stone.png" },
  { description = "Soft glassy dark gray stone", name = "soft_glassy_dark_gray_stone", tile = "mystical_lands_soft_glassy_dark_gray_stone.png" },
  { description = "Soft glassy dark olive stone", name = "soft_glassy_dark_olive_stone", tile = "mystical_lands_soft_glassy_dark_olive_stone.png" },
  { description = "Soft glassy gray blue stone", name = "soft_glassy_gray_blue_stone", tile = "mystical_lands_soft_glassy_gray_blue_stone.png" },
  { description = "Soft glassy light gray stone", name = "soft_glassy_light_gray_stone", tile = "mystical_lands_soft_glassy_light_gray_stone.png" },
  { description = "Soft glassy light olive stone", name = "soft_glassy_light_olive_stone", tile = "mystical_lands_soft_glassy_light_olive_stone.png" },
  { description = "Soft glassy pink stone", name = "soft_glassy_pink_stone", tile = "mystical_lands_soft_glassy_pink_stone.png" },
  { description = "Soft glassy red stone", name = "soft_glassy_red_stone", tile = "mystical_lands_soft_glassy_red_stone.png" },
  { description = "Soft glassy tan stone", name = "soft_glassy_tan_stone", tile = "mystical_lands_soft_glassy_tan_stone.png" },
  { description = "Soft glassy turquoise stone", name = "soft_glassy_turquoise_stone", tile = "mystical_lands_soft_glassy_turquoise_stone.png" },
  { description = "Soft glassy white stone", name = "soft_glassy_white_stone", tile = "mystical_lands_soft_glassy_white_stone.png" },
  { description = "Soft smooth black stone", name = "soft_smooth_black_stone", tile = "mystical_lands_soft_smooth_black_stone.png" },
  { description = "Soft smooth dark blue stone", name = "soft_smooth_dark_blue_stone", tile = "mystical_lands_soft_smooth_dark_blue_stone.png" },
  { description = "Soft smooth dark gray stone", name = "soft_smooth_dark_gray_stone", tile = "mystical_lands_soft_smooth_dark_gray_stone.png" },
  { description = "Soft smooth dark olive stone", name = "soft_smooth_dark_olive_stone", tile = "mystical_lands_soft_smooth_dark_olive_stone.png" },
  { description = "Soft smooth gray blue stone", name = "soft_smooth_gray_blue_stone", tile = "mystical_lands_soft_smooth_gray_blue_stone.png" },
  { description = "Soft smooth light gray stone", name = "soft_smooth_light_gray_stone", tile = "mystical_lands_soft_smooth_light_gray_stone.png" },
  { description = "Soft smooth light olive stone", name = "soft_smooth_light_olive_stone", tile = "mystical_lands_soft_smooth_light_olive_stone.png" },
  { description = "Soft smooth pink stone", name = "soft_smooth_pink_stone", tile = "mystical_lands_soft_smooth_pink_stone.png" },
  { description = "Soft smooth red stone", name = "soft_smooth_red_stone", tile = "mystical_lands_soft_smooth_red_stone.png" },
  { description = "Soft smooth tan stone", name = "soft_smooth_tan_stone", tile = "mystical_lands_soft_smooth_tan_stone.png" },
  { description = "Soft smooth turquoise stone", name = "soft_smooth_turquoise_stone", tile = "mystical_lands_soft_smooth_turquoise_stone.png" },
  { description = "Soft smooth white stone", name = "soft_smooth_white_stone", tile = "mystical_lands_soft_smooth_white_stone.png" },
  { description = "Very hard coarse grain black stone", name = "very_hard_coarse_grain_black_stone", tile = "mystical_lands_very_hard_coarse_grain_black_stone.png" },
  { description = "Very hard coarse grain dark blue stone", name = "very_hard_coarse_grain_dark_blue_stone", tile = "mystical_lands_very_hard_coarse_grain_dark_blue_stone.png" },
  { description = "Very hard coarse grain dark gray stone", name = "very_hard_coarse_grain_dark_gray_stone", tile = "mystical_lands_very_hard_coarse_grain_dark_gray_stone.png" },
  { description = "Very hard coarse grain dark olive stone", name = "very_hard_coarse_grain_dark_olive_stone", tile = "mystical_lands_very_hard_coarse_grain_dark_olive_stone.png" },
  { description = "Very hard coarse grain gray blue stone", name = "very_hard_coarse_grain_gray_blue_stone", tile = "mystical_lands_very_hard_coarse_grain_gray_blue_stone.png" },
  { description = "Very hard coarse grain light gray stone", name = "very_hard_coarse_grain_light_gray_stone", tile = "mystical_lands_very_hard_coarse_grain_light_gray_stone.png" },
  { description = "Very hard coarse grain light olive stone", name = "very_hard_coarse_grain_light_olive_stone", tile = "mystical_lands_very_hard_coarse_grain_light_olive_stone.png" },
  { description = "Very hard coarse grain pink stone", name = "very_hard_coarse_grain_pink_stone", tile = "mystical_lands_very_hard_coarse_grain_pink_stone.png" },
  { description = "Very hard coarse grain red stone", name = "very_hard_coarse_grain_red_stone", tile = "mystical_lands_very_hard_coarse_grain_red_stone.png" },
  { description = "Very hard coarse grain tan stone", name = "very_hard_coarse_grain_tan_stone", tile = "mystical_lands_very_hard_coarse_grain_tan_stone.png" },
  { description = "Very hard coarse grain turquoise stone", name = "very_hard_coarse_grain_turquoise_stone", tile = "mystical_lands_very_hard_coarse_grain_turquoise_stone.png" },
  { description = "Very hard coarse grain white stone", name = "very_hard_coarse_grain_white_stone", tile = "mystical_lands_very_hard_coarse_grain_white_stone.png" },
  { description = "Very hard fine grain black stone", name = "very_hard_fine_grain_black_stone", tile = "mystical_lands_very_hard_fine_grain_black_stone.png" },
  { description = "Very hard fine grain dark blue stone", name = "very_hard_fine_grain_dark_blue_stone", tile = "mystical_lands_very_hard_fine_grain_dark_blue_stone.png" },
  { description = "Very hard fine grain dark gray stone", name = "very_hard_fine_grain_dark_gray_stone", tile = "mystical_lands_very_hard_fine_grain_dark_gray_stone.png" },
  { description = "Very hard fine grain dark olive stone", name = "very_hard_fine_grain_dark_olive_stone", tile = "mystical_lands_very_hard_fine_grain_dark_olive_stone.png" },
  { description = "Very hard fine grain gray blue stone", name = "very_hard_fine_grain_gray_blue_stone", tile = "mystical_lands_very_hard_fine_grain_gray_blue_stone.png" },
  { description = "Very hard fine grain light gray stone", name = "very_hard_fine_grain_light_gray_stone", tile = "mystical_lands_very_hard_fine_grain_light_gray_stone.png" },
  { description = "Very hard fine grain light olive stone", name = "very_hard_fine_grain_light_olive_stone", tile = "mystical_lands_very_hard_fine_grain_light_olive_stone.png" },
  { description = "Very hard fine grain pink stone", name = "very_hard_fine_grain_pink_stone", tile = "mystical_lands_very_hard_fine_grain_pink_stone.png" },
  { description = "Very hard fine grain red stone", name = "very_hard_fine_grain_red_stone", tile = "mystical_lands_very_hard_fine_grain_red_stone.png" },
  { description = "Very hard fine grain tan stone", name = "very_hard_fine_grain_tan_stone", tile = "mystical_lands_very_hard_fine_grain_tan_stone.png" },
  { description = "Very hard fine grain turquoise stone", name = "very_hard_fine_grain_turquoise_stone", tile = "mystical_lands_very_hard_fine_grain_turquoise_stone.png" },
  { description = "Very hard fine grain white stone", name = "very_hard_fine_grain_white_stone", tile = "mystical_lands_very_hard_fine_grain_white_stone.png" },
  { description = "Very hard glassy black stone", name = "very_hard_glassy_black_stone", tile = "mystical_lands_very_hard_glassy_black_stone.png" },
  { description = "Very hard glassy dark blue stone", name = "very_hard_glassy_dark_blue_stone", tile = "mystical_lands_very_hard_glassy_dark_blue_stone.png" },
  { description = "Very hard glassy dark gray stone", name = "very_hard_glassy_dark_gray_stone", tile = "mystical_lands_very_hard_glassy_dark_gray_stone.png" },
  { description = "Very hard glassy dark olive stone", name = "very_hard_glassy_dark_olive_stone", tile = "mystical_lands_very_hard_glassy_dark_olive_stone.png" },
  { description = "Very hard glassy gray blue stone", name = "very_hard_glassy_gray_blue_stone", tile = "mystical_lands_very_hard_glassy_gray_blue_stone.png" },
  { description = "Very hard glassy light gray stone", name = "very_hard_glassy_light_gray_stone", tile = "mystical_lands_very_hard_glassy_light_gray_stone.png" },
  { description = "Very hard glassy light olive stone", name = "very_hard_glassy_light_olive_stone", tile = "mystical_lands_very_hard_glassy_light_olive_stone.png" },
  { description = "Very hard glassy pink stone", name = "very_hard_glassy_pink_stone", tile = "mystical_lands_very_hard_glassy_pink_stone.png" },
  { description = "Very hard glassy red stone", name = "very_hard_glassy_red_stone", tile = "mystical_lands_very_hard_glassy_red_stone.png" },
  { description = "Very hard glassy tan stone", name = "very_hard_glassy_tan_stone", tile = "mystical_lands_very_hard_glassy_tan_stone.png" },
  { description = "Very hard glassy turquoise stone", name = "very_hard_glassy_turquoise_stone", tile = "mystical_lands_very_hard_glassy_turquoise_stone.png" },
  { description = "Very hard glassy white stone", name = "very_hard_glassy_white_stone", tile = "mystical_lands_very_hard_glassy_white_stone.png" },
  { description = "Very hard smooth black stone", name = "very_hard_smooth_black_stone", tile = "mystical_lands_very_hard_smooth_black_stone.png" },
  { description = "Very hard smooth dark blue stone", name = "very_hard_smooth_dark_blue_stone", tile = "mystical_lands_very_hard_smooth_dark_blue_stone.png" },
  { description = "Very hard smooth dark gray stone", name = "very_hard_smooth_dark_gray_stone", tile = "mystical_lands_very_hard_smooth_dark_gray_stone.png" },
  { description = "Very hard smooth dark olive stone", name = "very_hard_smooth_dark_olive_stone", tile = "mystical_lands_very_hard_smooth_dark_olive_stone.png" },
  { description = "Very hard smooth gray blue stone", name = "very_hard_smooth_gray_blue_stone", tile = "mystical_lands_very_hard_smooth_gray_blue_stone.png" },
  { description = "Very hard smooth light gray stone", name = "very_hard_smooth_light_gray_stone", tile = "mystical_lands_very_hard_smooth_light_gray_stone.png" },
  { description = "Very hard smooth light olive stone", name = "very_hard_smooth_light_olive_stone", tile = "mystical_lands_very_hard_smooth_light_olive_stone.png" },
  { description = "Very hard smooth pink stone", name = "very_hard_smooth_pink_stone", tile = "mystical_lands_very_hard_smooth_pink_stone.png" },
  { description = "Very hard smooth red stone", name = "very_hard_smooth_red_stone", tile = "mystical_lands_very_hard_smooth_red_stone.png" },
  { description = "Very hard smooth tan stone", name = "very_hard_smooth_tan_stone", tile = "mystical_lands_very_hard_smooth_tan_stone.png" },
  { description = "Very hard smooth turquoise stone", name = "very_hard_smooth_turquoise_stone", tile = "mystical_lands_very_hard_smooth_turquoise_stone.png" },
  { description = "Very hard smooth white stone", name = "very_hard_smooth_white_stone", tile = "mystical_lands_very_hard_smooth_white_stone.png" },
  { description = "Very soft coarse grain black stone", name = "very_soft_coarse_grain_black_stone", tile = "mystical_lands_very_soft_coarse_grain_black_stone.png" },
  { description = "Very soft coarse grain dark blue stone", name = "very_soft_coarse_grain_dark_blue_stone", tile = "mystical_lands_very_soft_coarse_grain_dark_blue_stone.png" },
  { description = "Very soft coarse grain dark gray stone", name = "very_soft_coarse_grain_dark_gray_stone", tile = "mystical_lands_very_soft_coarse_grain_dark_gray_stone.png" },
  { description = "Very soft coarse grain dark olive stone", name = "very_soft_coarse_grain_dark_olive_stone", tile = "mystical_lands_very_soft_coarse_grain_dark_olive_stone.png" },
  { description = "Very soft coarse grain gray blue stone", name = "very_soft_coarse_grain_gray_blue_stone", tile = "mystical_lands_very_soft_coarse_grain_gray_blue_stone.png" },
  { description = "Very soft coarse grain light gray stone", name = "very_soft_coarse_grain_light_gray_stone", tile = "mystical_lands_very_soft_coarse_grain_light_gray_stone.png" },
  { description = "Very soft coarse grain light olive stone", name = "very_soft_coarse_grain_light_olive_stone", tile = "mystical_lands_very_soft_coarse_grain_light_olive_stone.png" },
  { description = "Very soft coarse grain pink stone", name = "very_soft_coarse_grain_pink_stone", tile = "mystical_lands_very_soft_coarse_grain_pink_stone.png" },
  { description = "Very soft coarse grain red stone", name = "very_soft_coarse_grain_red_stone", tile = "mystical_lands_very_soft_coarse_grain_red_stone.png" },
  { description = "Very soft coarse grain tan stone", name = "very_soft_coarse_grain_tan_stone", tile = "mystical_lands_very_soft_coarse_grain_tan_stone.png" },
  { description = "Very soft coarse grain turquoise stone", name = "very_soft_coarse_grain_turquoise_stone", tile = "mystical_lands_very_soft_coarse_grain_turquoise_stone.png" },
  { description = "Very soft coarse grain white stone", name = "very_soft_coarse_grain_white_stone", tile = "mystical_lands_very_soft_coarse_grain_white_stone.png" },
  { description = "Very soft fine grain black stone", name = "very_soft_fine_grain_black_stone", tile = "mystical_lands_very_soft_fine_grain_black_stone.png" },
  { description = "Very soft fine grain dark blue stone", name = "very_soft_fine_grain_dark_blue_stone", tile = "mystical_lands_very_soft_fine_grain_dark_blue_stone.png" },
  { description = "Very soft fine grain dark gray stone", name = "very_soft_fine_grain_dark_gray_stone", tile = "mystical_lands_very_soft_fine_grain_dark_gray_stone.png" },
  { description = "Very soft fine grain dark olive stone", name = "very_soft_fine_grain_dark_olive_stone", tile = "mystical_lands_very_soft_fine_grain_dark_olive_stone.png" },
  { description = "Very soft fine grain gray blue stone", name = "very_soft_fine_grain_gray_blue_stone", tile = "mystical_lands_very_soft_fine_grain_gray_blue_stone.png" },
  { description = "Very soft fine grain light gray stone", name = "very_soft_fine_grain_light_gray_stone", tile = "mystical_lands_very_soft_fine_grain_light_gray_stone.png" },
  { description = "Very soft fine grain light olive stone", name = "very_soft_fine_grain_light_olive_stone", tile = "mystical_lands_very_soft_fine_grain_light_olive_stone.png" },
  { description = "Very soft fine grain pink stone", name = "very_soft_fine_grain_pink_stone", tile = "mystical_lands_very_soft_fine_grain_pink_stone.png" },
  { description = "Very soft fine grain red stone", name = "very_soft_fine_grain_red_stone", tile = "mystical_lands_very_soft_fine_grain_red_stone.png" },
  { description = "Very soft fine grain tan stone", name = "very_soft_fine_grain_tan_stone", tile = "mystical_lands_very_soft_fine_grain_tan_stone.png" },
  { description = "Very soft fine grain turquoise stone", name = "very_soft_fine_grain_turquoise_stone", tile = "mystical_lands_very_soft_fine_grain_turquoise_stone.png" },
  { description = "Very soft fine grain white stone", name = "very_soft_fine_grain_white_stone", tile = "mystical_lands_very_soft_fine_grain_white_stone.png" },
  { description = "Very soft glassy black stone", name = "very_soft_glassy_black_stone", tile = "mystical_lands_very_soft_glassy_black_stone.png" },
  { description = "Very soft glassy dark blue stone", name = "very_soft_glassy_dark_blue_stone", tile = "mystical_lands_very_soft_glassy_dark_blue_stone.png" },
  { description = "Very soft glassy dark gray stone", name = "very_soft_glassy_dark_gray_stone", tile = "mystical_lands_very_soft_glassy_dark_gray_stone.png" },
  { description = "Very soft glassy dark olive stone", name = "very_soft_glassy_dark_olive_stone", tile = "mystical_lands_very_soft_glassy_dark_olive_stone.png" },
  { description = "Very soft glassy gray blue stone", name = "very_soft_glassy_gray_blue_stone", tile = "mystical_lands_very_soft_glassy_gray_blue_stone.png" },
  { description = "Very soft glassy light gray stone", name = "very_soft_glassy_light_gray_stone", tile = "mystical_lands_very_soft_glassy_light_gray_stone.png" },
  { description = "Very soft glassy light olive stone", name = "very_soft_glassy_light_olive_stone", tile = "mystical_lands_very_soft_glassy_light_olive_stone.png" },
  { description = "Very soft glassy pink stone", name = "very_soft_glassy_pink_stone", tile = "mystical_lands_very_soft_glassy_pink_stone.png" },
  { description = "Very soft glassy red stone", name = "very_soft_glassy_red_stone", tile = "mystical_lands_very_soft_glassy_red_stone.png" },
  { description = "Very soft glassy tan stone", name = "very_soft_glassy_tan_stone", tile = "mystical_lands_very_soft_glassy_tan_stone.png" },
  { description = "Very soft glassy turquoise stone", name = "very_soft_glassy_turquoise_stone", tile = "mystical_lands_very_soft_glassy_turquoise_stone.png" },
  { description = "Very soft glassy white stone", name = "very_soft_glassy_white_stone", tile = "mystical_lands_very_soft_glassy_white_stone.png" },
  { description = "Very soft smooth black stone", name = "very_soft_smooth_black_stone", tile = "mystical_lands_very_soft_smooth_black_stone.png" },
  { description = "Very soft smooth dark blue stone", name = "very_soft_smooth_dark_blue_stone", tile = "mystical_lands_very_soft_smooth_dark_blue_stone.png" },
  { description = "Very soft smooth dark gray stone", name = "very_soft_smooth_dark_gray_stone", tile = "mystical_lands_very_soft_smooth_dark_gray_stone.png" },
  { description = "Very soft smooth dark olive stone", name = "very_soft_smooth_dark_olive_stone", tile = "mystical_lands_very_soft_smooth_dark_olive_stone.png" },
  { description = "Very soft smooth gray blue stone", name = "very_soft_smooth_gray_blue_stone", tile = "mystical_lands_very_soft_smooth_gray_blue_stone.png" },
  { description = "Very soft smooth light gray stone", name = "very_soft_smooth_light_gray_stone", tile = "mystical_lands_very_soft_smooth_light_gray_stone.png" },
  { description = "Very soft smooth light olive stone", name = "very_soft_smooth_light_olive_stone", tile = "mystical_lands_very_soft_smooth_light_olive_stone.png" },
  { description = "Very soft smooth pink stone", name = "very_soft_smooth_pink_stone", tile = "mystical_lands_very_soft_smooth_pink_stone.png" },
  { description = "Very soft smooth red stone", name = "very_soft_smooth_red_stone", tile = "mystical_lands_very_soft_smooth_red_stone.png" },
  { description = "Very soft smooth tan stone", name = "very_soft_smooth_tan_stone", tile = "mystical_lands_very_soft_smooth_tan_stone.png" },
  { description = "Very soft smooth turquoise stone", name = "very_soft_smooth_turquoise_stone", tile = "mystical_lands_very_soft_smooth_turquoise_stone.png" },
  { description = "Very soft smooth white stone", name = "very_soft_smooth_white_stone", tile = "mystical_lands_very_soft_smooth_white_stone.png" }
}

for index, n in pairs(stone_nodes) do
  reg(
      mod .. n.name,
      {
        description = n.description,
        tiles = {n.tile},
        walkable = true,
        pointable = true,
        diggable = true,
        --sounds = default.node_sound_stone_defaults(),
        groups = {cracky = 3, stone = 1},
      }
    )
  end